### ISSUE TITLE
'>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by 6sz** [jdariasl/COVIDNET#1]
In the load_image function of the dataset.py file， 
        image2[image2>0]=255
        image2 = image2[:,:,0]
        mask = Image.fromarray(image2.astype('uint8'))
I can't understand what the purpose of this is.
In addition, is there any documentation for this code?
I hope you can help me.

**Comment by jdariasl** [comment]
The load_image function performs image equalization as part of the preprocessing steps. The equalization is performed using only the part of the image that contains information (removing the background of the RX). For doing that, the Equaliser requires a mask (take a look at the [PIL documentation](https://pillow.readthedocs.io/en/3.0.x/reference/ImageOps.html)), so that part of the code defines the mask to be used. This is a relevant step, especially if you perform lung segmentation as a previous stage in the pipeline.

**Comment by 6sz** [comment]
Thank you very much, I have solved the previous problem with your help, but when I use LungSegmentation.ipynb for image segmentation of data, is it normal to find a part of the image will be moved to a RemoveSegmented folder (no image segmentation can be made)?In addition, if you need to carry out Experiment 2 in your paper, what should I do for image cropping?I hope you can help me, thank you, please.

**Comment by jdariasl** [comment]
You right; sometimes, the Lung Segmenter is unable to find any lung region in the image and return an array of zeros. Those images are moved to a different folder because they cannot be used for Experiments 2 or 3, and for the sake of comparison, they were not used for experiment 1 either. The lung segmenter is proposed in [GitHub](https://github.com/imlab-uiip/lung-segmentation-2d). We used it without any modification so that a different model could be tested, or a segmenter fine-tuning process could also be carried out. 

The cropping of the images was made in MatLab. The script is also included in the repository at [link](https://github.com/jdariasl/COVIDNET/blob/master/MatLab_preprocessing/Script_Cropping_Image.m). Actually, this script does not perform a complex process and can be easily migrated to python.

**Comment by 6sz** [comment]
I see. Thank you very much.

**Comment by 6sz** [comment]
Hello, when I was getting COVID Data Save Lives Data, I found that authorization is required in the application. I have submitted the application, but I don't know whether it can be approved. Could you please share your Data set?(Use Google, cloud disk or whatever platform is convenient for you). thank you, please.

**Comment by jdariasl** [comment]
Unfortunately I can't, you must contact directly the owners of the data and sign a NDA for each data set.

**Comment by 6sz** [comment]
Oh, yes, thank you.I have already submitted the application and I should get the result tomorrow.
